var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,p,u){a!=Array.prototype&&a!=Object.prototype&&(a[p]=u.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(p){return $jscomp.SYMBOL_PREFIX+(p||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var p=0;return $jscomp.iteratorPrototype(function(){return p<a.length?{done:!1,value:a[p++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,p){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var u=0,h={next:function(){if(u<a.length){var z=u++;return{value:p(z,a[z]),done:!1}}h.next=function(){return{done:!0,value:void 0}};return h.next()}};h[Symbol.iterator]=function(){return h};return h};
$jscomp.polyfill=function(a,p,u,h){if(p){u=$jscomp.global;a=a.split(".");for(h=0;h<a.length-1;h++){var z=a[h];z in u||(u[z]={});u=u[z]}a=a[a.length-1];h=u[a];p=p(h);p!=h&&null!=p&&$jscomp.defineProperty(u,a,{configurable:!0,writable:!0,value:p})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
(function(a){function p(a){try{var f={};Object.keys(a).filter(function(a){return-1==["domain","test","version","schemaVersion"].indexOf(a)}).forEach(function(c){var e=a[c]||{},n=[];Object.keys(e).forEach(function(a){e[a].forEach(function(b){b.type=a;n.push(b)})});var b=u(n,"denial"===c||"fullPage"===c||"error"===c?"node":"text");b[0]&&(f[c]="string"===typeof b[0]||"number"===typeof b[0]?b[0]:!!b[0])})}catch(c){console&&console.debug&&console.debug("While calculating detector values",c)}return f}function u(a,
f,c){function e(b,c,f){if("node"===c)return b;if("text"===c)return b.map(function(b){var c=a.field||a.attribute,d=b;c?(c&&c.split(".")).forEach(function(a){d=d[a]}):d=b.text||b.innerText||b.textContent;return f?p(f,d):d})}function p(a,b){if(2<a.length){var c=new RegExp(a[0],a[1]);var f=a[2]}else c=new RegExp(a[0]),f=a[1];if(f){var e=c.exec(b),d=/^\$([0-9]+)$/.exec(f);if(e)return d[1]?(c=parseInt(d[1]),e[c]):b.replace(c,f)}else return console.warn("Sed without substitution",a),null}c=c||window.location.href;
if(Array.isArray(a))return a.map(function(a){var b=u(a,f,c);b&&Array.isArray(b)&&a.exclude&&(b=b.filter(function(b){return-1===a.exclude.indexOf(b)}));return b}).reduce(function(a,b){null!=b&&(Array.isArray(b)?b.forEach(function(b){null!=b&&a.push(b)}):a.push(b));return a},[]);if(!a)return null;c=c&&decodeURIComponent(c);var b=a.type,n=a.value,m=a.sed;"string"===typeof a&&(b="css",n=a);if("constant"===b)return[n];if("css"===b||"jquery"===b){f=f||(m?"text":"node");if(n){var k;"css"===b?k=document.querySelectorAll(n):
"jquery"===b&&window.$&&(k=window.$(n));b=Array.prototype.slice.call(k);return e(b,f,m)}throw"CSS selector value nto specified"+JSON.stringify(a);}if("url"===b){if(f&&"text"!==f)throw"URL selectors can only return text";f="text";b=c?c:decodeURIComponent(window.location.pathname);m&&(b=p(m,b));return[b]}if("xpath"===b){f=f||(m?"text":"node");b=h(n);if("string"===typeof b)return m?[p(m,b)]:[b];if(Array.isArray(b))return e(b,f,m)}else{if("meta"===b)return f=f||"text",m=document.getElementsByTagName("meta"),
m=_.filter(m,function(a){return a.property===n||a.name===n}),_.map(m,function(a){return a.content});throw"Cannot evaluate type:"+b;}}function h(a,f){f=f||document;if(document.evaluate){var c=document.evaluate(a,f,null,0,null);if(0<c.resultType&&4>c.resultType){var e=null;2===c.resultType?e=c.stringValue:3===c.resultType?e=""+c.booleanValue:1===c.resultType&&(e=""+c.numberValue);return e}if(4<=c.resultType){e=null;if(4===c.resultType||5===c.resultType){e=[];for(var n;null!=(n=c.iterateNext());)e.push(n)}else if(8===
c.resultType||9===c.resultType)e=[c.singleNodeValue];else if(6===c.resultType||7===c.resultType)e=[c.snapshotItem()];return e}}else return[]}function z(a,f){var c=document.createElement("script");c.src=a;c.type="text/javascript";c.async=!0;if(f)for(var e in f)if(null!=e)if(c.dataset)c.dataset[e]=f[e];else{var n=f[e],b=e.replace(/[A-Z]/g,function(a){return"-"+a[0].toLowerCase()});c.setAttribute("data-"+b,n)}(e=document.getElementsByTagName("script"))&&0<e.length?e[0].parentNode.insertBefore(c,e[0]):
document.head.appendChild(c);return c}function R(a){return(Math.random().toString(36)+"00000000000000000").slice(2,a+2)}function F(n,f){function c(){console.log("Piwik is not available")}if(a.Hermes)return a.Hermes;var e={userRHKey:n,install:F,config:function(b){function e(){if(document.hidden){O=new Date;var a={activePageDuration:O.getTime()-P.getTime(),activeElementHref:document.activeElement&&document.activeElement.href};w(x.INACTIVE,a)}else P=new Date,a={inactivePageDuration:P.getTime()-O.getTime(),
activeElementHref:document.activeElement&&document.activeElement.href},w(x.ACTIVE,a)}function k(){if(""===C(G+x.CLOSE)){J(G+x.CLOSE,!0,1);var a={openPageDuration:(new Date).getTime()-Q,activeElementHref:document.activeElement&&document.activeElement.href};w(x.CLOSE,a)}}function h(a){try{var b=a&&a.sendPageSrc,c=a.evalPage&&a.detectors;try{var d=c&&p(a.detectors)||{}}catch(T){d={}}""===C(G+x.OPEN)&&J(G+x.OPEN,!0,1);w(x.OPEN,d,b)}catch(T){w(x.ERROR,{error:"3."+T.message},!1)}}function r(a,b){function c(){if(!g){g=
!0;for(var a=0;a<f.length;a++)f[a].fn.call(b,f[a].ctx);f=[]}}function d(){"complete"===document.readyState&&c()}b.addEventListener?b.addEventListener("beforeunload",k):b.onbeforeunload=k;document.addEventListener&&document.addEventListener("visibilitychange",e);b=b||b;var f=[],g=!1,n=!1;b[a||"hermesDocReady"]=function(a,e){g?setTimeout(function(){a(e)},1):(f.push({fn:a,ctx:e}),"complete"===document.readyState||!document.attachEvent&&"interactive"===document.readyState?setTimeout(c,1):n||(document.addEventListener?
(document.addEventListener("DOMContentLoaded",c,!1),b.addEventListener("load",c,!1)):(document.attachEvent("onreadystatechange",d),b.attachEvent("onload",c)),n=!0))}}function B(){for(var a=document.getElementsByTagName("script"),b,c=0;c<a.length;c++){var d=a.item(c);if(d.src&&-1!=d.src.indexOf("CaptureData")){b=d;break}}b&&b.parentNode&&b.parentNode.removeChild(b)}function w(c,d,e){function k(){if(a.XMLHttpRequest){var b=new XMLHttpRequest;if("withCredentials"in b)b.withCredentials=!0;else if("undefined"!=
typeof XDomainRequest)b=new XDomainRequest;else return}else b=new ActiveXObject("Microsoft.XMLHTTP");return b}var p=d&&d.id,q=p&&0<(""+p.trim()).length;q&&(d.id="####");b.sendGet&&B();var h="NA";try{h=d.error||""}catch(E){}var m=null;try{var l=C("detector");if(l&&(l=JSON.parse(l),l.denial&&l.denial.xpath)){var r=u(l.denial.xpath);r&&0<r.length&&(m=!0)}}catch(E){}b.sendGet&&z(f+"/api/CaptureData?userRHKey="+encodeURIComponent(n)+"&actionType="+c+"&cookie="+encodeURIComponent(H)+"&scookie="+encodeURIComponent(I)+
"&eMsg="+encodeURIComponent(h)+(e?"&reqDet=true":"")+(m?"&den=true":""));if(b.sendPost){l={};r="";m=k();try{m.onload=function(b){function g(a,b,d,e,h){e=e||document.documentElement.innerHTML;if(q)try{var l=p.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");e=e.replace(new RegExp(l,"g"),"####")}catch(X){console&&console.debug&&console.debug(X)}d=d||0;b=b||4E5;h=h||Math.ceil(e.length/b);l=e.slice(d*b,Math.min((d+1)*b,e.length));l="userRHKey="+encodeURIComponent(n)+"&hrmEvtId="+a+"&maxLength="+b+"&chunkNo="+d+
"&numOfChunks="+h+"&pageSource="+encodeURIComponent(l);var m=k();m.onload=function(c){d<h-1&&g(a,b,d+1,e,h)};m.open("POST",f+"/api/CaptureData?userRHKey="+encodeURIComponent(n)+"&actionType="+c+"&cookie="+encodeURIComponent(H)+"&scookie="+encodeURIComponent(I),!0);"withCredentials"in m&&m.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");m.send(l)}b&&b.target&&(b.target.response&&(b=JSON.parse(b.target.response),b.evtId&&"open"==c&&(a.Hermes.hrmEvtId=b.evtId,"deferred"===
e&&g(b.evtId,4E5))),v&&v.dataset&&v.dataset.chromeExtId&&(a.postMessage({msg:"R!",actionType:c,data:d},"*"),chrome.runtime.sendMessage(v.dataset.chromeExtId,{msg:"R"},function(a){})))}}catch(E){r=r+"1."+E.message+"\n"}try{var w=null,x=null,A=null,D=C(K),S=C(L);g&&(g.memory&&(w={jsHeapSizeLimit:g.memory.jsHeapSizeLimit,totalJSHeapSize:g.memory.totalJSHeapSize,usedJSHeapSize:g.memory.usedJSHeapSize}),g.timing&&(x={connectEnd:g.timing.connectEnd,connectStart:g.timing.connectStart,domComplete:g.timing.domComplete,
domContentLoadedEventEnd:g.timing.domContentLoadedEventEnd,domContentLoadedEventStart:g.timing.domContentLoadedEventStart,domInteractive:g.timing.domInteractive,domLoading:g.timing.domLoading,domainLookupEnd:g.timing.domainLookupEnd,domainLookupStart:g.timing.domainLookupStart,fetchStart:g.timing.fetchStart,loadEventEnd:g.timing.loadEventEnd,loadEventStart:g.timing.loadEventStart,navigationStart:g.timing.navigationStart,redirectEnd:g.timing.redirectEnd,redirectStart:g.timing.redirectStart,requestStart:g.timing.requestStart,
responseEnd:g.timing.responseEnd,responseStart:g.timing.responseStart,secureConnectionStart:g.timing.secureConnectionStart,unloadEventEnd:g.timing.unloadEventEnd,unloadEventStart:g.timing.unloadEventStart}),g.navigation&&(A={redirectCount:g.navigation.redirectCount,type:g.navigation.type}),l.performance={memory:w,navigation:A,timing:x});l.actionType=c;l.userCookie=D;l.userSessionCookie=S;l.userDate=new Date;l.currentPath=G;l.browserName=y;l.fullVersion=t;l.majorVersion=M;l.screenWidth=Y;l.screenHeight=
Z;l.language=aa;l.osName=ba;l.appName=ca;l.userAgent=da;l.referrer=ea;l.data=d;l.refEvtId=a.Hermes.hrmEvtId}catch(E){r=r+"2."+E.message+"\n"}m.open("POST",f+"/api/CaptureData?userRHKey="+encodeURIComponent(n)+"&actionType="+c+"&cookie="+encodeURIComponent(H)+"&scookie="+encodeURIComponent(I)+"&reqDet=2&eMsg="+encodeURIComponent(h),!0);"withCredentials"in m&&m.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");0<r.length&&(l.data={error:r});if(m&&a.JSON){h="userRHKey="+
encodeURIComponent(n)+"&data="+encodeURIComponent(JSON.stringify(l));if(e&&!0===e){D=void 0;if(e){D=document.documentElement.innerHTML;if(q)try{var W=p.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");D=D.replace(new RegExp(W,"g"),"####")}catch(E){console&&console.debug&&console.debug(E)}D=e?encodeURIComponent(D):null}h=h+"&pageSource="+D}else"deferred"===e&&(h=h+"&pageSource="+encodeURIComponent("\x3c!-- Deferred --\x3e"));m.send(h)}}}function J(a,b,c,d){if(U===c)var e="expires=Fri, 31 Dec 9999 23:59:59 GMT";
else c&&(e=new Date,e.setTime(e.getTime()+6E4*c),e="expires="+e.toUTCString());document.cookie=a+"="+b+"; "+e+(d?"; path="+d:"")}function C(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1);if(0===d.indexOf(a))return d.substring(a.length,d.length)}return""}var d=a.sessionStorage&&a.sessionStorage.getItem("hermes_config")||a.localStorage&&a.localStorage.getItem("hermes_config");d&&(d=JSON.parse(d));for(var A in d)b[A]=d[A];var F=null==
b.sendBodyLevel?!0:3<=b.sendBodyLevel?!0:2===b.sendBodyLevel?"deferred":!1;var V=b.detectors;d=null;a.location.search&&0<a.location.search.indexOf("rmqSelect=")&&(d=a.location.search.indexOf("rmqSelect=")+10,A=a.location.search.indexOf("&",d),d=-1!=A?a.location.search.substring(d,A):a.location.search.substring(d),d=decodeURIComponent(d),console.log("Picking rmqSelect:"+d));if(d&&("stage"===d?(b.installRemarq="https://rmrqstage.redlink.com/groveMain.bundle.js",b.rmqApiBase="https://rmrqstage.redlink.com/api"):
"beta"===d?(b.installRemarq="https://rmrqbeta.redlink.com/groveMain.bundle.js",b.rmqApiBase="https://rmrqbeta.redlink.com/api"):(b.installRemarq="https://"+d+"/groveMain.bundle.js",b.rmqApiBase="https://"+d+"/api"),a.sessionStorage))try{a.sessionStorage.setItem("hermes_config",JSON.stringify(b))}catch(S){}if(b.installRemarq)d=z(b.installRemarq,{apiBase:b.rmqApiBase}),d.onload=function(d){b.sendPiwik&&c();if(b.sendPost||b.sendGet)r("hermesDocReady",a),hermesDocReady(h,{evalPage:!0,detectors:V,sendPageSrc:F})},
d.onerror=d.onload;else if(b.sendPiwik&&c(),b.sendPost||b.sendGet)r("hermesDocReady",a),hermesDocReady(h,{evalPage:!0,detectors:V,sendPageSrc:F});var K="hrmTracker",L="hrmTracker_S",U="forever",H=C(K),I=C(L);H||(J(K,R(10),U,"/"),H=C(K));I||(J(L,R(10),null,"/"),I=C(L));var x={OPEN:"open",CLOSE:"close",ACTIVE:"active",INACTIVE:"inactive",ERROR:"error"},P=new Date,O=new Date,G=a.location.href,g=a.performance,Q=g&&g.timing&&g.timing.requestStart||(new Date).getTime();d=navigator.userAgent;var y=navigator.appName,
t=""+parseFloat(navigator.appVersion),M=parseInt(navigator.appVersion,10),q,N;var Y=a.screen?screen.width:0;var Z=a.screen?screen.height:0;var aa=navigator.language||navigator.userLanguage||"(Not supported)",ba=-1!=navigator.appVersion.indexOf("Win")?"Windows":-1!=navigator.appVersion.indexOf("Mac")?"MacOS":-1!=navigator.appVersion.indexOf("X11")?"UNIX":-1!=navigator.appVersion.indexOf("Linux")?"Linux":-1!=navigator.appVersion.indexOf("Android")?"Android":-1!=navigator.appVersion.indexOf("Iphone")?
"Iphone":"Unknown OS",ca=navigator.appName,da=navigator.userAgent,ea=document.referrer;-1!=(q=d.indexOf("OPR/"))?(y="Opera",t=d.substring(q+4)):-1!=(q=d.indexOf("Opera"))?(y="Opera",t=d.substring(q+6),-1!=(q=d.indexOf("Version"))&&(t=d.substring(q+8))):-1!=(q=d.indexOf("MSIE"))?(y="Microsoft Internet Explorer",t=d.substring(q+5)):-1!=(q=d.indexOf("Chrome"))?(y="Chrome",t=d.substring(q+7)):-1!=(q=d.indexOf("Safari"))?(y="Safari",t=d.substring(q+7),-1!=(q=d.indexOf("Version"))&&(t=d.substring(q+8))):
-1!=(q=d.indexOf("Firefox"))?(y="Firefox",t=d.substring(q+8)):(A=d.lastIndexOf(" ")+1)<(q=d.lastIndexOf("/"))&&(y=d.substring(A,q),t=d.substring(q+1),y.toLowerCase()==y.toUpperCase()&&(y=navigator._appName));-1!=(N=t.indexOf(";"))&&(t=t.substring(0,N));-1!=(N=t.indexOf(" "))&&(t=t.substring(0,N));M=parseInt(""+t,10);isNaN(M)&&(t=""+parseFloat(navigator.appVersion),M=parseInt(navigator.appVersion,10))},installDetector:function(a){var b=_getCookie("detector"),c=JSON.stringify(a);b!==c&&(_setCookie("detector",
JSON.stringify(a),null,"/"),e.detector=a)}},k=document.domain;k&&0==k.indexOf("www.")&&(k=k.substr(4));k=encodeURIComponent(k);z(f+"/api/config?userRHKey="+n+"&domain="+k);return e}for(var B=document.getElementsByTagName("script"),v,k=0;k<B.length;k++){var w=B.item(k);if(w.src&&-1!=w.src.indexOf("hermes")){v=w;break}}if(v){k=v.src.indexOf("?");var r=v.src.indexOf("/hermes.js");v.src.substring(0,r);r={};if(-1!=k)for(B=v.src.substring(k+1).split("&"),k=0;k<B.length;k++){w=B[k].substring(0,B[k].indexOf("="));
var Q=B[k].substring(B[k].indexOf("=")+1);r[w]=Q}(r=r.userRHKey)||(r=v.data&&v.data.userRHKey);r||(r="None")}else console&&console.error&&console.error("Cannot find script tag. Is script included as hermes.js");k="//hermes.redlink.com";v.dataset&&v.dataset.captureBase&&(k=v.dataset.captureBase);a.Hermes=F(r,k)})(window);
